backend:
  name: github
  repo: Voormedia/saskia-project
  branch: main
media_folder: "source/images/uploads"

collections:
  - label: "Sections"
    name: "sections"
    files:
      - label: "Contact"
        name: "contact"
        file: "data/contact.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Company name, name: company-name, widget: string}
          - {label: Company address, name: company-address, widget: markdown}
          - {label: Phone number, name: phone, widget: string}
          - {label: Email address, name: email, widget: string}
